"""
DeepONet with Standard (Fixed) Trunk for Time Series Forecasting
- Channel-independent processing: works with any number of channels
- Trunk has learnable weights (NOT generated by Branch)
- Branch only outputs coefficients B
"""
import math
import torch
import torch.nn as nn
import torch.nn.functional as F


class FNN(nn.Module):
    """Feedforward Neural Network"""
    def __init__(self, input_dim, output_dim, depth, width, activation='relu', dropout=0.0):
        super(FNN, self).__init__()

        layers = []
        layers.append(nn.Linear(input_dim, width))
        layers.append(self._get_activation(activation))
        if dropout > 0.0:
            layers.append(nn.Dropout(dropout))

        for _ in range(depth - 2):
            layers.append(nn.Linear(width, width))
            layers.append(self._get_activation(activation))
            if dropout > 0.0:
                layers.append(nn.Dropout(dropout))

        layers.append(nn.Linear(width, output_dim))

        self.net = nn.Sequential(*layers)
        self._initialize()

    def _get_activation(self, activation):
        if activation == 'relu':
            return nn.ReLU()
        elif activation == 'gelu':
            return nn.GELU()
        elif activation == 'tanh':
            return nn.Tanh()
        else:
            return nn.ReLU()

    def _initialize(self):
        for module in self.net:
            if isinstance(module, nn.Linear):
                nn.init.xavier_normal_(module.weight)
                nn.init.constant_(module.bias, 0)

    def forward(self, x):
        return self.net(x)


class Model(nn.Module):
    """
    Channel-Independent DeepONet with Standard (Fixed) Trunk Network
    + Residual Linear skip connection for stable optimization

    Architecture per channel:
      Linear(x_channel) → base prediction [batch, pred_len]   (residual)
      Branch(x_channel) → Coefficients B [batch, width]
      Trunk(t_future)   → Basis functions Φ [pred_len, width]  (FIXED, shared)
      Output = Linear(x) + B ⊗ Φ
    """

    def __init__(self, configs):
        super(Model, self).__init__()

        self.seq_len = configs.seq_len
        self.pred_len = configs.pred_len
        self.use_norm = getattr(configs, 'use_norm', True)

        self.branch_depth = getattr(configs, 'branch_depth', 3)
        self.trunk_depth = getattr(configs, 'trunk_depth', 3)
        self.width = getattr(configs, 'deeponet_width', 64)
        self.activation = getattr(configs, 'activation', 'gelu')
        self.dropout = getattr(configs, 'dropout', 0.0)

        # Residual linear: direct mapping from input to output
        self.linear_skip = nn.Linear(self.seq_len, self.pred_len)

        # Branch: input time series → coefficients B
        branch_dim = self.seq_len
        self.branch_net = FNN(branch_dim, self.width, self.branch_depth,
                             self.width * 4, self.activation, self.dropout)

        # Trunk: fixed learnable network, time → basis functions
        # Use Fourier features as input for richer basis
        self.n_freq = 32
        trunk_input_dim = 1 + 2 * self.n_freq  # t + sin/cos features
        self.trunk_net = FNN(trunk_input_dim, self.width, self.trunk_depth,
                            self.width * 2, self.activation)

        # Bias
        self.bias = nn.Parameter(torch.zeros([1]))

    def _get_fourier_features(self, t):
        """
        t: [pred_len, 1]
        Returns: [pred_len, 1 + 2*n_freq]
        """
        freqs = torch.arange(1, self.n_freq + 1, dtype=t.dtype, device=t.device)
        # [pred_len, n_freq]
        sin_features = torch.sin(2 * math.pi * freqs.unsqueeze(0) * t)
        cos_features = torch.cos(2 * math.pi * freqs.unsqueeze(0) * t)
        return torch.cat([t, sin_features, cos_features], dim=-1)

    def _forward_single_channel(self, x_ch):
        """
        x_ch: [batch, seq_len]
        Returns: [batch, pred_len]
        """
        # Residual: direct linear prediction
        base = self.linear_skip(x_ch)  # [batch, pred_len]

        # Branch: input → coefficients
        B = self.branch_net(x_ch)  # [batch, width]

        # Trunk: Fourier time features → basis functions
        t_output = torch.linspace(0, 1, self.pred_len, dtype=x_ch.dtype, device=x_ch.device)
        t_output = t_output.unsqueeze(-1)  # [pred_len, 1]
        t_fourier = self._get_fourier_features(t_output)  # [pred_len, 1+2*n_freq]
        Phi = self.trunk_net(t_fourier)  # [pred_len, width]

        # DeepONet output: sum_k B[b, k] * Phi[q, k]
        deeponet_out = torch.einsum('bp,qp->bq', B, Phi)  # [batch, pred_len]

        output = base + deeponet_out + self.bias
        return output

    def forecast(self, x_enc, x_mark_enc=None, x_dec=None, x_mark_dec=None):
        """
        x_enc: [batch, seq_len, channels]
        Returns: [batch, pred_len, channels]
        """
        batch_size, seq_len, n_channels = x_enc.shape

        if self.use_norm:
            means = x_enc.mean(1, keepdim=True).detach()
            x_enc = x_enc - means
            stdev = torch.sqrt(torch.var(x_enc, dim=1, keepdim=True, unbiased=False) + 1e-5)
            x_enc = x_enc / stdev

        outputs = []
        for ch in range(n_channels):
            x_ch = x_enc[:, :, ch]  # [batch, seq_len]
            out_ch = self._forward_single_channel(x_ch)  # [batch, pred_len]
            outputs.append(out_ch)

        output = torch.stack(outputs, dim=-1)  # [batch, pred_len, channels]

        if self.use_norm:
            output = output * stdev
            output = output + means

        return output

    def forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec):
        dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
        return dec_out[:, -self.pred_len:, :]
